spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: system
    password: 1234
  security:
    user.name: system
    user.password: 1234

#logging:
#  level:
#    org.hibernate.type: TRACE
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.transaction: DEBUG